#配置开始==================
#每个玩家进服的时候都会给一个，当拿着这个玩意右键的时候打开菜单主页，特殊值可以不限定，当特殊值为x时默认匹配所有，特殊值默认为0,当这个值为空(null{在Yml文件内用~表示})时不适用快捷工具！
快捷工具: '347:0'
货币单位: 金币
检测更新: true
检测更新间隔: 21600
#假如玩家在这个时间段内双击，将无法用快捷工具多次打开主页，防止刷屏
屏蔽玩家双击间隔: 500
仅允许白名单管理菜单: false
白名单: []