name: Knickers
main: cn.winfxk.knickers.Knickers
api:
- 1.0.0
version: 3.0
load: POSTWORLD
website: http://Winfxk.cn
description: 全能菜单插件，支持自定义功能、自定义变量、自定义货币等
author: Winfxk
loadbefore:
- EconomyAPI
permissions:
   Knickers.Command.main:
      description: Knickers主命令
      default: true